//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using capaEntidad;
    
    public partial class PFINALEntities : DbContext
    {
        public PFINALEntities()
            : base("name=PFINALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DEPARTAMENTO> DEPARTAMENTOS { get; set; }
        public virtual DbSet<LOGUEO> LOGUEOs { get; set; }
        public virtual DbSet<USUARIO> USUARIOS { get; set; }
        public virtual DbSet<DOCUMENTO> DOCUMENTOS { get; set; }
    
        public virtual int SP_PRUEBA_SECU()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PRUEBA_SECU");
        }
    
        public virtual ObjectResult<SP_REPORTE_ALLDOCUMENTS_Result> SP_REPORTE_ALLDOCUMENTS(Nullable<int> dOCUMENT)
        {
            var dOCUMENTParameter = dOCUMENT.HasValue ?
                new ObjectParameter("DOCUMENT", dOCUMENT) :
                new ObjectParameter("DOCUMENT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_REPORTE_ALLDOCUMENTS_Result>("SP_REPORTE_ALLDOCUMENTS", dOCUMENTParameter);
        }
    
        public virtual ObjectResult<SP_REPORTE_DEPARTAMENTOS_Result> SP_REPORTE_DEPARTAMENTOS(string dEPARTAMENTO)
        {
            var dEPARTAMENTOParameter = dEPARTAMENTO != null ?
                new ObjectParameter("DEPARTAMENTO", dEPARTAMENTO) :
                new ObjectParameter("DEPARTAMENTO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_REPORTE_DEPARTAMENTOS_Result>("SP_REPORTE_DEPARTAMENTOS", dEPARTAMENTOParameter);
        }
    
        public virtual ObjectResult<SP_REPORTE_DEPDEST_Result> SP_REPORTE_DEPDEST(string dEPT)
        {
            var dEPTParameter = dEPT != null ?
                new ObjectParameter("DEPT", dEPT) :
                new ObjectParameter("DEPT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_REPORTE_DEPDEST_Result>("SP_REPORTE_DEPDEST", dEPTParameter);
        }
    
        public virtual ObjectResult<SP_REPORTE_DEPORG_Result> SP_REPORTE_DEPORG(string dEPT)
        {
            var dEPTParameter = dEPT != null ?
                new ObjectParameter("DEPT", dEPT) :
                new ObjectParameter("DEPT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_REPORTE_DEPORG_Result>("SP_REPORTE_DEPORG", dEPTParameter);
        }
    
        public virtual ObjectResult<SP_REPORTE_DOCFOREMPLOYEES_Result> SP_REPORTE_DOCFOREMPLOYEES(Nullable<int> uSR)
        {
            var uSRParameter = uSR.HasValue ?
                new ObjectParameter("USR", uSR) :
                new ObjectParameter("USR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_REPORTE_DOCFOREMPLOYEES_Result>("SP_REPORTE_DOCFOREMPLOYEES", uSRParameter);
        }
    
        public virtual ObjectResult<SP_REPORTE_RANGOFECHA_Result> SP_REPORTE_RANGOFECHA(string yEARSTART, string yEARFINISH)
        {
            var yEARSTARTParameter = yEARSTART != null ?
                new ObjectParameter("YEARSTART", yEARSTART) :
                new ObjectParameter("YEARSTART", typeof(string));
    
            var yEARFINISHParameter = yEARFINISH != null ?
                new ObjectParameter("YEARFINISH", yEARFINISH) :
                new ObjectParameter("YEARFINISH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_REPORTE_RANGOFECHA_Result>("SP_REPORTE_RANGOFECHA", yEARSTARTParameter, yEARFINISHParameter);
        }
    
        public virtual ObjectResult<SP_REPORTE_USUARIOS_Result> SP_REPORTE_USUARIOS(string nOMBRE)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_REPORTE_USUARIOS_Result>("SP_REPORTE_USUARIOS", nOMBREParameter);
        }
    }
}
