//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTAMENTO
    {
        public int ID_DEPARTAMENTO { get; set; }
        public string NOMBRE_DPTO { get; set; }
        public string SIGLAS { get; set; }
    }
}
