//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTO
    {
        public int ID_DOCUMENTO { get; set; }
        public string TIPO { get; set; }
        public int UP_USUARIO { get; set; }
        public string DEPARTAMENTO_ORIGEN { get; set; }
        public string DEPARTAMENTO_DESTINO { get; set; }
        public string NUMERACION { get; set; }
        public System.DateTime FECHA { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
