//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGUEO
    {
        public int ID_LOGIN { get; set; }
        public string USUARIO_L { get; set; }
        public string CORREO_L { get; set; }
        public string PASSWORD_L { get; set; }
    }
}
