//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.DOCUMENTOS = new HashSet<DOCUMENTO>();
        }
    
        public int ID_USUARIO { get; set; }
        public string NOMBRE_U { get; set; }
        public string APELLIDO { get; set; }
        public string CEDULA { get; set; }
        public string TELEFONO { get; set; }
        public string CORREO_U { get; set; }
        public string DEPARTAMENTO_U { get; set; }
        public string CARGO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCUMENTO> DOCUMENTOS { get; set; }
    }
}
